self.addEventListener('install',event=>{self.skipWaiting();});
self.addEventListener('activate',event=>{
  event.waitUntil(
    Promise.all([
      self.registration.unregister(),
      caches.keys().then(keys=>Promise.all(
        keys.filter(k=>k.startsWith('workout-note-pwa-')).map(k=>caches.delete(k))
      ))
    ])
  );
});
